### ISSUE TITLE
Feature request: User pages in Wiki

### ISSUE THREAD

**Issue by deleterium** [vinibiavatti1/TuiCss#35]
Hello and nice project!

I would suggest to add page on wiki where people using your UI can let their page address. It would be nice also for beginners to see real pages with the code. Of course, it must have a big advice that these pages are not supported/endorsed by TuiCss owner.

Thanks,
Rui.

**Comment by vinibiavatti1** [comment]
Hi Rui!
Thanks for the suggestion. I'm gonna check the best way to create this kind of page in the wiki. I will create something like a "showcase" there.
If you have some project links and images to share, it will be nice ;)

Thanks,
Vini.

**Comment by deleterium** [comment]
First of all, congratulation for the wiki page and examples. They are pretty complete!

The page I've created is a blockchain game to remember the old times of BBS. It is currently online at https://stellarduel.space

Some screenshots:
![stellar1](https://user-images.githubusercontent.com/54009773/170266796-5aa8c548-5403-4a93-b98e-a1e8c8a1b185.png)

![stellar2](https://user-images.githubusercontent.com/54009773/170266813-91f8e119-509e-4669-a1f6-7a0a34821d97.png)

![stellar3](https://user-images.githubusercontent.com/54009773/170266826-ca15d811-1f99-40d8-97af-8589ab8722cb.png)

**Comment by vinibiavatti1** [comment]
OMG! This is pretty awesome!  Congratulations for this project. I'm feeling super happy you liked the TuiCSS and used it to a personal project. Amazing :')!

I'm updating the showcase page, and wanted to make it like you said, but after searching a bit, I think I cannot turn only one page of the wiki as public edition. I must set the entire wiki as public to do it. Because of this limitation, I think it will be better to create a new issue badge to purpose a new content to the showcase page. Or we can change the wiki to public, but I'm not sure it would be a good idea. What do you think? If you have some other idea, please share here that we will analyze it better :).

Thanks again!!!

**Comment by vinibiavatti1** [comment]
I created a new template issue for showcase proposals. Please, take a look there. If you like this way, enjoy it to create a new issue with the content of your project.

**Comment by deleterium** [comment]
I think it is OK to open a issue to be listed (I just did it!). The wiki is already complete, so it is not needed to allow any user to make modifications on the completed pages just because the showcase.
